import { StyleSheet } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";

export default StyleSheet.create({
    container2: {
        flex: 2,
        backgroundColor: '#fff',
        height: '100%',
        width: '100%',
        alignItems: 'center',
      },
      container3: {
        flexDirection: 'row',
      },
      container4: {
        marginTop: 10,
        alignItems:'center',
        backgroundColor: '#ffffff00',
        width: '90%',
        height: 70,
        borderWidth: 2, 
        borderColor: '#81D5F5',
        borderRadius: 10,
        justifyContent: 'center',
      },
      container5: {
        alignItems:'center',
        backgroundColor: '#ffffff00',
        width: '80%',
        height: 50,
        borderWidth: 2, 
        borderTopWidth: 0,
        borderRadius: 10,
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderColor: '#039FD8',
        justifyContent: 'center',
      },
      container6: {
        width: '90%',
        flexDirection: 'row',
        alignItems: 'center',
      },
      container7: {
        marginTop: 10,
        alignItems:'center',
        backgroundColor: '#ffffff00',
        width: '90%',
        height: 50,
        borderWidth: 2, 
        borderColor: '#81D5F5',
        borderBottomWidth: 5,
        borderRadius: 10,
        justifyContent: 'center',
      },
      container8: {
        width:'100%',
        height:'100%',
        alignContent: 'center',
      },
      desc: {
        fontSize: 30,
        alignSelf: 'center',
        marginBottom: 10,
        color: '#fff'
      },
      desc2: {
        fontSize: RFValue(6, 400),
        width: '100%',
        height: '35%',
        borderBottomWidth: 5,
        borderBottomColor: '#22894d',
        borderRadius: 5,
        backgroundColor: '#2bb063',
        alignSelf: 'center',
        textAlign: 'center',
        textAlignVertical: 'top',
        color: '#fff',
      },
      desc3: {
        fontSize: RFValue(6, 300),
        width: '90%',
        height: 120,
        borderBottomWidth: 5,
        borderBottomColor: '#2a9cb7',
        borderRadius: 5,
        backgroundColor: '#34c3e5',
        alignSelf: 'center',
        textAlign: 'center',
        alignContent: 'center',
        alignItems: 'center',
        textAlignVertical: 'center',
        color: '#fff',
        marginTop: 10,
      },
      container0: {
        height: '10%',
        width: '75%',
      },
      btn_iniciar: {
        backgroundColor: '#ffffff00',
        opacity: 1,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: "#fff",
        marginTop: 10,
        alignSelf: 'center',
        padding: 10,
        width: '75%',
        height: 80,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
      },
      btn_creditos: {
        backgroundColor: '#ffffff00',
        opacity: 0.6,
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 15,
        marginTop: 5,
        marginRight: 2,
        width: '75%',
        height: 80,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
      },
      btn_info: {
        backgroundColor: '#ffffff00',
        opacity: 0.5,
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 15,
        marginTop: 5,
        marginLeft: 2,
        width: 98,
        height: 80,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
      },
      btns_inicio: {
        backgroundColor: '#ffffff00',
        flexDirection: 'row',
        borderWidth: 1,
        borderRadius: 15,
        marginTop: 10,
        width: '90%',
        height: 150,
        alignSelf: 'center',
        alignItems: 'center',
      },
      image_background: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: "center",
        alignItems: "center"
      },
      image_logo: {
        width: 300,
        height: 300,
        marginBottom: 30,
      },
      image_btns_inicio: {
        width: 100,
        height: 100,
        marginRight: 30,
        marginLeft: 30,
      },
      image_profile: {
        width: 100,
        height: 100,
        marginRight: 30,
        marginLeft: 19,
      },
      text1: {
        fontSize: 25,
        color: '#fff',
      },
      text2: {
        fontSize: 25,
        color: '#000',
      },
      text3: {
        fontSize: 20,
        color: '#000',
        alignSelf: 'flex-start',
      },
      text5: {
        opacity: 0.5,
        fontSize: 15,
        color: '#000',
      },
      text4: {
        fontSize: 25,
        color: '#000',
      },
})