import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container2: {
        flex: 2,
        backgroundColor: '#fff',
        alignItems: 'center',
      },
      container3: {
        flexDirection: 'row',
      },
      container4: {
        marginTop: 10,
        alignItems:'center',
        backgroundColor: '#81D5F5',
        width: 350,
        height: 80,
        borderRadius: 10,
        justifyContent: 'center',
      },
      container5: {
        alignItems:'center',
        backgroundColor: '#039FD8',
        width: 300,
        height: 50,
        borderRadius: 10,
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        justifyContent: 'center',
      },
      btn_iniciar: {
        backgroundColor: '#ffffff00',
        opacity: 1,
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: "#fff",
        marginTop: 10,
        alignSelf: 'center',
        padding: 10,
        width: 300,
        height: 80,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
      },
      btn_creditos: {
        backgroundColor: '#ffffff00',
        opacity: 0.5,
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 15,
        marginTop: 5,
        marginRight: 2,
        width: 198,
        height: 80,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
      },
      btn_info: {
        backgroundColor: '#ffffff00',
        opacity: 0.5,
        borderWidth: 1,
        borderColor: "#fff",
        borderRadius: 15,
        marginTop: 5,
        marginLeft: 2,
        width: 98,
        height: 80,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
      },
      btns_inicio: {
        backgroundColor: '#ffffff00',
        flexDirection: 'row',
        borderWidth: 1,
        borderRadius: 15,
        marginTop: 10,
        width: 370,
        height: 150,
        alignSelf: 'center',
        alignItems: 'center',
      },
      image_background: {
        flex: 1,
        width: 400,
        height: 870,
        justifyContent: "center",
        alignItems: "center"
      },
      image_logo: {
        width: 300,
        height: 300,
        marginBottom: 100,
      },
      image_btns_inicio: {
        width: 100,
        height: 100,
        marginRight: 30,
        marginLeft: 30,
      },
      text1: {
        fontSize: 25,
        color: '#fff',
      },
      text2: {
        fontSize: 25,
        color: '#000',
    },
})